version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: test_proj_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 30s
      timeout: 10s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      API_TOKEN: '7427205707:AAGqC3GbfYxp4OVphWGZCPCffhR4xGERO4A'
      DATABASE_URL: 'postgresql://admin:admin@db/test_proj_db'
    volumes:
      - .:/app

volumes:
  pgdata:
  pgadmin-data:
